version: "3.8"

services:
  # app:
  #   build: .
  #   container_name: disposable-nodejs
  #   networks:
  #     - custom_network
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - redis
  #     - kafka
  #   environment:
  #     - POSTGRES_URL=postgresql://user:password@postgres:5432/mydatabase
  #     - REDIS_URL=redis://redis:6379
  #     - KAFKA_BROKER=kafka:9092
  #   restart: always

  postgres:
    image: postgres:latest
    container_name: postgres-disposable-nodejs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-disposable-nodejs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-disposable-nodejs
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper-disposable-nodejs"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka-disposable-nodejs"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  mongodb_data:
